from .CHATBOT import CHATBOT_SYSTEM_PROMPT
from .SCRAPER import SCRAPER_SYSTEM_PROMPT
from .SUPERVISOR import SUPERVISOR_SYSTEM_PROMPT
from .ANALYST import ANALYST_SYSTEM_PROMPT


__all__ = [
    "CHATBOT_SYSTEM_PROMPT",
    "SCRAPER_SYSTEM_PROMPT",
    "SUPERVISOR_SYSTEM_PROMPT",
    "ANALYST_SYSTEM_PROMPT",
]

